#!/bin/bash

echo "🔧 GitHub Repository Umbenennung"
echo "================================"
echo ""
echo "Das Repo heißt auf GitHub noch 'briefing'."
echo "Neue Name soll sein: perplexity-mcp-briefing"
echo ""
echo "📋 Schritte:"
echo ""
echo "1. Öffne: https://github.com/AndreasDietzel/briefing/settings"
echo "2. Unter 'Repository name' eingeben: perplexity-mcp-briefing"
echo "3. Klicke 'Rename'"
echo ""
echo "4. Dann lokal aktualisieren:"
echo "   git remote set-url origin https://github.com/AndreasDietzel/perplexity-mcp-briefing.git"
echo ""
echo "5. Prüfen:"
echo "   git remote -v"
echo ""
echo "6. Fertig! 🎉"
